//note, the purpose of this file is to ensure that nationalities are properly represented and that people are shown as they are celebrating their 
//unique and natural characteristics. There is no intention to offend or discriminate on any level. 
//The values contained here are meant to generate basic values that can be used in simulation games. They are reductionistic and far too simple to accurately represent the peoples of these nations
//Race is a social construct, but one that has been used to marginalize, enslave, and otherwise deeply harm many good people throughout human history
//I implore anyone using this file for any reason to please do so with the intention of celebrating the people's of these nations as the are
//If anyone disagrees with the probabilities I've created, please contact me directly or create your own version. 

// alt keycodes for Côte d’Ivoire are 0244 and 0146
// alt keycodes for São Tomé e Príncipe are 0227, 0237 and 130 
// alt keycode for the Åland Islands is 0197 

function nations(){
    return [									
        {nation: "Albania",	toptier:1,	nationstartingfirstletter:1,	groupid:13,	isocountry:"AL",	nationid:1,	asn:0,	lt:54,	md:46,	dk:0},
        {nation: "Andorra",	toptier:1,	nationstartingfirstletter:1,	groupid:28,	isocountry:"AD",	nationid:2,	asn:0,	lt:33,	md:67,	dk:0},
        {nation: "Armenia",	toptier:1,	nationstartingfirstletter:1,	groupid:14,	isocountry:"AM",	nationid:3,	asn:0,	lt:27,	md:73,	dk:0},
        {nation: "Austria",	toptier:1,	nationstartingfirstletter:1,	groupid:15,	isocountry:"AT",	nationid:4,	asn:0,	lt:71,	md:16,	dk:13},
        {nation: "Azerbaijan",	toptier:1,	nationstartingfirstletter:1,	groupid:16,	isocountry:"AZ",	nationid:5,	asn:0,	lt:55,	md:45,	dk:0},
        {nation: "Belarus",	toptier:1,	nationstartingfirstletter:1,	groupid:4,	isocountry:"BY",	nationid:6,	asn:0,	lt:33,	md:67,	dk:0},
        {nation: "Belgium",	toptier:1,	nationstartingfirstletter:1,	groupid:18,	isocountry:"BE",	nationid:7,	asn:0,	lt:39,	md:15,	dk:46},
        {nation: "Bosnia and Herzegovina",	toptier:1,	nationstartingfirstletter:1,	groupid:19,	isocountry:"BA",	nationid:8,	asn:0,	lt:84,	md:16,	dk:0},
        {nation: "Bulgaria",	toptier:1,	nationstartingfirstletter:1,	groupid:21,	isocountry:"BG",	nationid:9,	asn:0,	lt:75,	md:12,	dk:13},
        {nation: "Croatia",	toptier:1,	nationstartingfirstletter:1,	groupid:0,	isocountry:"HR",	nationid:10,	asn:0,	lt:84,	md:16,	dk:0},
        {nation: "Cyprus",	toptier:1,	nationstartingfirstletter:1,	groupid:2,	isocountry:"CY",	nationid:11,	asn:0,	lt:32,	md:59,	dk:9},
        {nation: "Czech Republic",	toptier:1,	nationstartingfirstletter:1,	groupid:32,	isocountry:"CZ",	nationid:12,	asn:0,	lt:98,	md:2,	dk:0},
        {nation: "Denmark",	toptier:1,	nationstartingfirstletter:1,	groupid:33,	isocountry:"DK",	nationid:13,	asn:0,	lt:70,	md:20,	dk:10},
        {nation: "England",	toptier:1,	nationstartingfirstletter:1,	groupid:38,	isocountry:"GB",	nationid:14,	asn:0,	lt:33,	md:21,	dk:46},
        {nation: "Montenegro",	toptier:1,	nationstartingfirstletter:1,	groupid:0,	isocountry:"ME",	nationid:15,	asn:0,	lt:64,	md:36,	dk:0},
        {nation: "Faroe Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:49,	isocountry:"FO",	nationid:16,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Finland",	toptier:1,	nationstartingfirstletter:1,	groupid:1,	isocountry:"FI",	nationid:17,	asn:0,	lt:66,	md:20,	dk:14},
        {nation: "France",	toptier:1,	nationstartingfirstletter:1,	groupid:41,	isocountry:"FR",	nationid:18,	asn:0,	lt:16,	md:20,	dk:64},
        {nation: "North Macedonia",	toptier:1,	nationstartingfirstletter:1,	groupid:21,	isocountry:"MK",	nationid:19,	asn:0,	lt:78,	md:22,	dk:0},
        {nation: "Georgia",	toptier:1,	nationstartingfirstletter:1,	groupid:46,	isocountry:"GE",	nationid:20,	asn:0,	lt:74,	md:26,	dk:0},
        {nation: "Germany",	toptier:1,	nationstartingfirstletter:1,	groupid:48,	isocountry:"DE",	nationid:21,	asn:0,	lt:58,	md:17,	dk:25},
        {nation: "Greece",	toptier:1,	nationstartingfirstletter:1,	groupid:2,	isocountry:"GR",	nationid:22,	asn:0,	lt:67,	md:33,	dk:0},
        {nation: "Hungary",	toptier:1,	nationstartingfirstletter:1,	groupid:52,	isocountry:"HU",	nationid:23,	asn:0,	lt:73,	md:18,	dk:9},
        {nation: "Iceland",	toptier:1,	nationstartingfirstletter:1,	groupid:53,	isocountry:"IS",	nationid:24,	asn:0,	lt:77,	md:14,	dk:9},
        {nation: "Republic of Ireland",	toptier:1,	nationstartingfirstletter:1,	groupid:102,	isocountry:"IE",	nationid:25,	asn:0,	lt:62,	md:14,	dk:24},
        {nation: "Israel",	toptier:1,	nationstartingfirstletter:1,	groupid:57,	isocountry:"IL",	nationid:26,	asn:0,	lt:20,	md:42,	dk:38},
        {nation: "Italy",	toptier:1,	nationstartingfirstletter:1,	groupid:58,	isocountry:"IT",	nationid:27,	asn:0,	lt:68,	md:21,	dk:11},
        {nation: "Latvia",	toptier:1,	nationstartingfirstletter:1,	groupid:35,	isocountry:"LV",	nationid:28,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Liechtenstein",	toptier:1,	nationstartingfirstletter:1,	groupid:47,	isocountry:"LI",	nationid:29,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Lithuania",	toptier:1,	nationstartingfirstletter:1,	groupid:98,	isocountry:"LT",	nationid:30,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Luxembourg",	toptier:1,	nationstartingfirstletter:1,	groupid:63,	isocountry:"LU",	nationid:31,	asn:0,	lt:41,	md:17,	dk:42},
        {nation: "Malta",	toptier:1,	nationstartingfirstletter:1,	groupid:68,	isocountry:"MT",	nationid:32,	asn:0,	lt:20,	md:80,	dk:0},
        {nation: "Moldova",	toptier:1,	nationstartingfirstletter:1,	groupid:3,	isocountry:"MD",	nationid:33,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Holland",	toptier:1,	nationstartingfirstletter:1,	groupid:34,	isocountry:"NL",	nationid:34,	asn:0,	lt:30,	md:26,	dk:44},
        {nation: "Northern Ireland",	toptier:1,	nationstartingfirstletter:1,	groupid:56,	isocountry:"GB",	nationid:35,	asn:0,	lt:80,	md:16,	dk:4},
        {nation: "Norway",	toptier:1,	nationstartingfirstletter:1,	groupid:75,	isocountry:"NO",	nationid:36,	asn:0,	lt:65,	md:16,	dk:19},
        {nation: "Poland",	toptier:1,	nationstartingfirstletter:1,	groupid:78,	isocountry:"PL",	nationid:37,	asn:0,	lt:95,	md:5,	dk:0},
        {nation: "Portugal",	toptier:1,	nationstartingfirstletter:1,	groupid:6,	isocountry:"PT",	nationid:38,	asn:0,	lt:21,	md:41,	dk:38},
        {nation: "Romania",	toptier:1,	nationstartingfirstletter:1,	groupid:3,	isocountry:"RO",	nationid:39,	asn:0,	lt:84,	md:16,	dk:0},
        {nation: "Russia",	toptier:1,	nationstartingfirstletter:1,	groupid:4,	isocountry:"RU",	nationid:40,	asn:0,	lt:91,	md:9,	dk:0},
        {nation: "San Marino",	toptier:1,	nationstartingfirstletter:1,	groupid:58,	isocountry:"SM",	nationid:41,	asn:0,	lt:68,	md:21,	dk:11},
        {nation: "Scotland",	toptier:1,	nationstartingfirstletter:1,	groupid:80,	isocountry:"GB",	nationid:42,	asn:0,	lt:85,	md:11,	dk:4},
        {nation: "Slovakia",	toptier:1,	nationstartingfirstletter:1,	groupid:32,	isocountry:"SK",	nationid:43,	asn:0,	lt:93,	md:7,	dk:0},
        {nation: "Slovenia",	toptier:1,	nationstartingfirstletter:1,	groupid:82,	isocountry:"SI",	nationid:44,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Spain",	toptier:1,	nationstartingfirstletter:1,	groupid:5,	isocountry:"ES",	nationid:45,	asn:0,	lt:41,	md:54,	dk:5},
        {nation: "Sweden",	toptier:1,	nationstartingfirstletter:1,	groupid:87,	isocountry:"SE",	nationid:46,	asn:0,	lt:59,	md:20,	dk:21},
        {nation: "Switzerland",	toptier:1,	nationstartingfirstletter:1,	groupid:88,	isocountry:"CH",	nationid:47,	asn:0,	lt:39,	md:27,	dk:34},
        {nation: "Turkey",	toptier:1,	nationstartingfirstletter:1,	groupid:91,	isocountry:"TR",	nationid:48,	asn:0,	lt:50,	md:50,	dk:0},
        {nation: "Ukraine",	toptier:1,	nationstartingfirstletter:1,	groupid:93,	isocountry:"UA",	nationid:49,	asn:0,	lt:96,	md:4,	dk:0},
        {nation: "Wales",	toptier:1,	nationstartingfirstletter:1,	groupid:95,	isocountry:"GB",	nationid:50,	asn:0,	lt:70,	md:17,	dk:13},
        {nation: "Serbia",	toptier:1,	nationstartingfirstletter:1,	groupid:0,	isocountry:"RS",	nationid:51,	asn:0,	lt:80,	md:20,	dk:0},
        {nation: "Argentina",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"AR",	nationid:52,	asn:0,	lt:24,	md:76,	dk:0},
        {nation: "Bolivia",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"BO",	nationid:53,	asn:0,	lt:0,	md:94,	dk:6},
        {nation: "Brazil",	toptier:1,	nationstartingfirstletter:1,	groupid:20,	isocountry:"BR",	nationid:54,	asn:0,	lt:7,	md:54,	dk:39},
        {nation: "Chile",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"CL",	nationid:55,	asn:0,	lt:14,	md:83,	dk:3},
        {nation: "Colombia",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"CO",	nationid:56,	asn:0,	lt:1,	md:32,	dk:67},
        {nation: "Ecuador",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"EC",	nationid:57,	asn:0,	lt:1,	md:43,	dk:56},
        {nation: "Paraguay",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"PY",	nationid:58,	asn:0,	lt:5,	md:95,	dk:0},
        {nation: "Peru",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"PE",	nationid:59,	asn:0,	lt:2,	md:73,	dk:25},
        {nation: "Uruguay",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"UY",	nationid:60,	asn:0,	lt:19,	md:77,	dk:4},
        {nation: "Venezuela",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"VE",	nationid:61,	asn:0,	lt:7,	md:77,	dk:16},
        {nation: "Anguilla",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"AI",	nationid:62,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Antigua and Barbuda",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"AG",	nationid:63,	asn:0,	lt:0,	md:56,	dk:44},
        {nation: "Aruba",	toptier:1,	nationstartingfirstletter:1,	groupid:26,	isocountry:"AW",	nationid:64,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Bahamas",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"BS",	nationid:65,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Barbados",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"BB",	nationid:66,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Belize",	toptier:1,	nationstartingfirstletter:1,	groupid:97,	isocountry:"BZ",	nationid:67,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Bermuda",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"BM",	nationid:68,	asn:0,	lt:0,	md:36,	dk:64},
        {nation: "British Virgin Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"VG",	nationid:69,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Canada",	toptier:1,	nationstartingfirstletter:1,	groupid:74,	isocountry:"CA",	nationid:70,	asn:0,	lt:20,	md:21,	dk:59},
        {nation: "Cayman Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"KY",	nationid:71,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Costa Rica",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"CR",	nationid:72,	asn:0,	lt:7,	md:69,	dk:24},
        {nation: "Cuba",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"CU",	nationid:73,	asn:0,	lt:0,	md:32,	dk:68},
        {nation: "Dominica",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"DM",	nationid:74,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "International",	toptier:1,	nationstartingfirstletter:1,	groupid:38,	isocountry:"",	nationid:75,	asn:0,	lt:33,	md:34,	dk:33},
        {nation: "El Salvador",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"SV",	nationid:76,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "Grenada",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"GD",	nationid:77,	asn:0,	lt:0,	md:7,	dk:93},
        {nation: "Guatemala",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"GT",	nationid:78,	asn:0,	lt:18,	md:82,	dk:0},
        {nation: "Guyana",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"GY",	nationid:79,	asn:0,	lt:0,	md:24,	dk:76},
        {nation: "Haiti",	toptier:1,	nationstartingfirstletter:1,	groupid:27,	isocountry:"HT",	nationid:80,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Honduras",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"HN",	nationid:81,	asn:0,	lt:0,	md:46,	dk:54},
        {nation: "Jamaica",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"JM",	nationid:82,	asn:0,	lt:0,	md:20,	dk:80},
        {nation: "Mexico",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"MX",	nationid:83,	asn:0,	lt:6,	md:92,	dk:2},
        {nation: "Montserrat",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"MS",	nationid:84,	asn:0,	lt:0,	md:19,	dk:81},
        {nation: "Curaçao",	toptier:1,	nationstartingfirstletter:1,	groupid:24,	isocountry:"AN",	nationid:85,	asn:0,	lt:0,	md:25,	dk:75},
        {nation: "Nicaragua",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"NI",	nationid:86,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "Panama",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"PA",	nationid:87,	asn:0,	lt:3,	md:37,	dk:60},
        {nation: "Puerto Rico",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"PR",	nationid:88,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "St. Kitts and Nevis",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"KN",	nationid:89,	asn:0,	lt:0,	md:14,	dk:86},
        {nation: "St. Lucia",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"LC",	nationid:90,	asn:0,	lt:0,	md:38,	dk:62},
        {nation: "St. Vincent and the Grenadines",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"VC",	nationid:91,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Suriname",	toptier:1,	nationstartingfirstletter:1,	groupid:34,	isocountry:"SR",	nationid:92,	asn:0,	lt:0,	md:18,	dk:82},
        {nation: "Trinidad and Tobago",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"TT",	nationid:93,	asn:0,	lt:0,	md:14,	dk:86},
        {nation: "Turks and Caicos Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"TC",	nationid:94,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "United States",	toptier:1,	nationstartingfirstletter:1,	groupid:74,	isocountry:"US",	nationid:95,	asn:0,	lt:60,	md:20,	dk:20},
        {nation: "US Virgin Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"VI",	nationid:96,	asn:0,	lt:0,	md:67,	dk:33},
        {nation: "Algeria",	toptier:1,	nationstartingfirstletter:1,	groupid:65,	isocountry:"DZ",	nationid:97,	asn:0,	lt:7,	md:84,	dk:9},
        {nation: "Angola",	toptier:1,	nationstartingfirstletter:1,	groupid:12,	isocountry:"AO",	nationid:98,	asn:0,	lt:0,	md:4,	dk:96},
        {nation: "Benin",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"BJ",	nationid:99,	asn:0,	lt:0,	md:5,	dk:95},
        {nation: "Botswana",	toptier:1,	nationstartingfirstletter:1,	groupid:11,	isocountry:"BW",	nationid:100,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Burkina Faso",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"BF",	nationid:101,	asn:0,	lt:0,	md:4,	dk:96},
        {nation: "Burundi",	toptier:1,	nationstartingfirstletter:1,	groupid:29,	isocountry:"BI",	nationid:102,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Cameroon",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"CM",	nationid:103,	asn:0,	lt:0,	md:4,	dk:96},
        {nation: "Cape Verde Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:12,	isocountry:"CV",	nationid:104,	asn:0,	lt:1,	md:12,	dk:87},
        {nation: "Central African Republic",	toptier:1,	nationstartingfirstletter:1,	groupid:30,	isocountry:"CF",	nationid:105,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Chad",	toptier:1,	nationstartingfirstletter:1,	groupid:43,	isocountry:"TD",	nationid:106,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Congo",	toptier:1,	nationstartingfirstletter:1,	groupid:29,	isocountry:"CG",	nationid:107,	asn:0,	lt:0,	md:11,	dk:89},
        {nation: "Côte d’Ivoire",	toptier:1,	nationstartingfirstletter:1,	groupid:31,	isocountry:"CI",	nationid:108,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Djibouti",	toptier:1,	nationstartingfirstletter:1,	groupid:51,	isocountry:"DJ",	nationid:109,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Congo DR",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"CD",	nationid:110,	asn:0,	lt:0,	md:4,	dk:96},
        {nation: "Egypt",	toptier:1,	nationstartingfirstletter:1,	groupid:37,	isocountry:"EG",	nationid:111,	asn:0,	lt:5,	md:95,	dk:0},
        {nation: "Equatorial Guinea",	toptier:1,	nationstartingfirstletter:1,	groupid:5,	isocountry:"GQ",	nationid:112,	asn:0,	lt:0,	md:8,	dk:92},
        {nation: "Eritrea",	toptier:1,	nationstartingfirstletter:1,	groupid:51,	isocountry:"ER",	nationid:113,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Ethiopia",	toptier:1,	nationstartingfirstletter:1,	groupid:40,	isocountry:"ET",	nationid:114,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Gabon",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"GA",	nationid:115,	asn:0,	lt:0,	md:24,	dk:76},
        {nation: "Gambia",	toptier:1,	nationstartingfirstletter:1,	groupid:45,	isocountry:"GM",	nationid:116,	asn:0,	lt:0,	md:4,	dk:96},
        {nation: "Ghana",	toptier:1,	nationstartingfirstletter:1,	groupid:7,	isocountry:"GH",	nationid:117,	asn:0,	lt:0,	md:2,	dk:98},
        {nation: "Guinea",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"GN",	nationid:118,	asn:0,	lt:0,	md:4,	dk:96},
        {nation: "Guinea-Bissau",	toptier:1,	nationstartingfirstletter:1,	groupid:12,	isocountry:"GW",	nationid:119,	asn:0,	lt:0,	md:2,	dk:98},
        {nation: "Kenya",	toptier:1,	nationstartingfirstletter:1,	groupid:36,	isocountry:"KE",	nationid:120,	asn:0,	lt:0,	md:6,	dk:94},
        {nation: "Lesotho",	toptier:1,	nationstartingfirstletter:1,	groupid:85,	isocountry:"LS",	nationid:121,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Liberia",	toptier:1,	nationstartingfirstletter:1,	groupid:7,	isocountry:"LR",	nationid:122,	asn:0,	lt:8,	md:-1,	dk:93},
        {nation: "Libya",	toptier:1,	nationstartingfirstletter:1,	groupid:65,	isocountry:"LY",	nationid:123,	asn:0,	lt:13,	md:31,	dk:56},
        {nation: "Madagascar",	toptier:1,	nationstartingfirstletter:1,	groupid:64,	isocountry:"MG",	nationid:124,	asn:0,	lt:0,	md:49,	dk:51},
        {nation: "Malawi",	toptier:1,	nationstartingfirstletter:1,	groupid:99,	isocountry:"MW",	nationid:125,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Mali",	toptier:1,	nationstartingfirstletter:1,	groupid:43,	isocountry:"ML",	nationid:126,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Mauritania",	toptier:1,	nationstartingfirstletter:1,	groupid:43,	isocountry:"MR",	nationid:127,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Mauritius",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"MU",	nationid:128,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "Morocco",	toptier:1,	nationstartingfirstletter:1,	groupid:65,	isocountry:"MA",	nationid:129,	asn:0,	lt:1,	md:89,	dk:10},
        {nation: "Mozambique",	toptier:1,	nationstartingfirstletter:1,	groupid:12,	isocountry:"MZ",	nationid:130,	asn:0,	lt:0,	md:-1,	dk:101},
        {nation: "Namibia",	toptier:1,	nationstartingfirstletter:1,	groupid:71,	isocountry:"NA",	nationid:131,	asn:0,	lt:7,	md:0,	dk:93},
        {nation: "Niger",	toptier:1,	nationstartingfirstletter:1,	groupid:43,	isocountry:"NE",	nationid:132,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Nigeria",	toptier:1,	nationstartingfirstletter:1,	groupid:73,	isocountry:"NG",	nationid:133,	asn:0,	lt:0,	md:2,	dk:98},
        {nation: "Rwanda",	toptier:1,	nationstartingfirstletter:1,	groupid:29,	isocountry:"RW",	nationid:134,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "São Tomé e Príncipe",	toptier:1,	nationstartingfirstletter:1,	groupid:12,	isocountry:"ST",	nationid:135,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Senegal",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"SN",	nationid:136,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Seychelles",	toptier:1,	nationstartingfirstletter:1,	groupid:7,	isocountry:"SC",	nationid:137,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Sierra Leone",	toptier:1,	nationstartingfirstletter:1,	groupid:7,	isocountry:"SL",	nationid:138,	asn:0,	lt:0,	md:5,	dk:95},
        {nation: "Somalia",	toptier:1,	nationstartingfirstletter:1,	groupid:51,	isocountry:"SO",	nationid:139,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "South Africa",	toptier:1,	nationstartingfirstletter:1,	groupid:84,	isocountry:"ZA",	nationid:140,	asn:0,	lt:1,	md:9,	dk:90},
        {nation: "Sudan",	toptier:1,	nationstartingfirstletter:1,	groupid:37,	isocountry:"SD",	nationid:141,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Eswatini",	toptier:1,	nationstartingfirstletter:1,	groupid:83,	isocountry:"SZ",	nationid:142,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Tanzania",	toptier:1,	nationstartingfirstletter:1,	groupid:36,	isocountry:"TZ",	nationid:143,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Togo",	toptier:1,	nationstartingfirstletter:1,	groupid:42,	isocountry:"TG",	nationid:144,	asn:0,	lt:0,	md:8,	dk:92},
        {nation: "Tunisia",	toptier:1,	nationstartingfirstletter:1,	groupid:65,	isocountry:"TN",	nationid:145,	asn:0,	lt:6,	md:81,	dk:13},
        {nation: "Uganda",	toptier:1,	nationstartingfirstletter:1,	groupid:36,	isocountry:"UG",	nationid:146,	asn:0,	lt:0,	md:7,	dk:93},
        {nation: "Zambia",	toptier:1,	nationstartingfirstletter:1,	groupid:100,	isocountry:"ZM",	nationid:147,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Zimbabwe",	toptier:1,	nationstartingfirstletter:1,	groupid:101,	isocountry:"ZW",	nationid:148,	asn:0,	lt:0,	md:12,	dk:88},
        {nation: "Afghanistan",	toptier:1,	nationstartingfirstletter:1,	groupid:76,	isocountry:"AF",	nationid:149,	asn:0,	lt:50,	md:50,	dk:0},
        {nation: "Bahrain",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"BH",	nationid:150,	asn:0,	lt:33,	md:67,	dk:0},
        {nation: "Bangladesh",	toptier:1,	nationstartingfirstletter:1,	groupid:17,	isocountry:"BD",	nationid:151,	asn:0,	lt:0,	md:67,	dk:33},
        {nation: "Bhutan",	toptier:1,	nationstartingfirstletter:1,	groupid:72,	isocountry:"BT",	nationid:152,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Brunei Darussalam",	toptier:1,	nationstartingfirstletter:1,	groupid:66,	isocountry:"BN",	nationid:153,	asn:1,	lt:0,	md:90,	dk:10},
        {nation: "Cambodia",	toptier:1,	nationstartingfirstletter:1,	groupid:23,	isocountry:"KH",	nationid:154,	asn:1,	lt:0,	md:90,	dk:10},
        {nation: "China PR",	toptier:1,	nationstartingfirstletter:1,	groupid:9,	isocountry:"CN",	nationid:155,	asn:1,	lt:2,	md:98,	dk:0},
        {nation: "Guam",	toptier:1,	nationstartingfirstletter:1,	groupid:25,	isocountry:"GU",	nationid:157,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Hong Kong",	toptier:1,	nationstartingfirstletter:1,	groupid:9,	isocountry:"HK",	nationid:158,	asn:1,	lt:20,	md:80,	dk:0},
        {nation: "India",	toptier:1,	nationstartingfirstletter:1,	groupid:54,	isocountry:"IN",	nationid:159,	asn:0,	lt:0,	md:61,	dk:39},
        {nation: "Indonesia",	toptier:1,	nationstartingfirstletter:1,	groupid:55,	isocountry:"ID",	nationid:160,	asn:1,	lt:67,	md:33,	dk:0},
        {nation: "Iran",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"IR",	nationid:161,	asn:0,	lt:7,	md:93,	dk:0},
        {nation: "Iraq",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"IQ",	nationid:162,	asn:0,	lt:17,	md:83,	dk:0},
        {nation: "Japan",	toptier:1,	nationstartingfirstletter:1,	groupid:10,	isocountry:"JP",	nationid:163,	asn:1,	lt:4,	md:94,	dk:2},
        {nation: "Jordan",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"JO",	nationid:164,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "Kazakhstan",	toptier:1,	nationstartingfirstletter:1,	groupid:59,	isocountry:"KZ",	nationid:165,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Korea DPR",	toptier:1,	nationstartingfirstletter:1,	groupid:60,	isocountry:"KP",	nationid:166,	asn:1,	lt:33,	md:67,	dk:0},
        {nation: "Korea Republic",	toptier:1,	nationstartingfirstletter:1,	groupid:60,	isocountry:"KR",	nationid:167,	asn:1,	lt:7,	md:93,	dk:0},
        {nation: "Kuwait",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"KW",	nationid:168,	asn:0,	lt:17,	md:83,	dk:0},
        {nation: "Kyrgyzstan",	toptier:1,	nationstartingfirstletter:1,	groupid:61,	isocountry:"KG",	nationid:169,	asn:0,	lt:33,	md:67,	dk:0},
        {nation: "Laos",	toptier:1,	nationstartingfirstletter:1,	groupid:62,	isocountry:"LA",	nationid:170,	asn:1,	lt:0,	md:90,	dk:10},
        {nation: "Lebanon",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"LB",	nationid:171,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "Macau",	toptier:1,	nationstartingfirstletter:1,	groupid:9,	isocountry:"MO",	nationid:172,	asn:1,	lt:33,	md:67,	dk:0},
        {nation: "Malaysia",	toptier:1,	nationstartingfirstletter:1,	groupid:66,	isocountry:"MY",	nationid:173,	asn:1,	lt:0,	md:90,	dk:10},
        {nation: "Maldives",	toptier:1,	nationstartingfirstletter:1,	groupid:67,	isocountry:"MV",	nationid:174,	asn:0,	lt:0,	md:67,	dk:33},
        {nation: "Mongolia",	toptier:1,	nationstartingfirstletter:1,	groupid:70,	isocountry:"MN",	nationid:175,	asn:1,	lt:33,	md:67,	dk:0},
        {nation: "Myanmar",	toptier:1,	nationstartingfirstletter:1,	groupid:22,	isocountry:"MM",	nationid:176,	asn:1,	lt:0,	md:67,	dk:33},
        {nation: "Nepal",	toptier:1,	nationstartingfirstletter:1,	groupid:72,	isocountry:"NP",	nationid:177,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Oman",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"OM",	nationid:178,	asn:0,	lt:0,	md:33,	dk:67},
        {nation: "Pakistan",	toptier:1,	nationstartingfirstletter:1,	groupid:76,	isocountry:"PK",	nationid:179,	asn:0,	lt:0,	md:67,	dk:33},
        {nation: "Palestine",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"PS",	nationid:180,	asn:0,	lt:0,	md:100,	dk:0},
        {nation: "Philippines",	toptier:1,	nationstartingfirstletter:1,	groupid:77,	isocountry:"PH",	nationid:181,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Qatar",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"QA",	nationid:182,	asn:0,	lt:2,	md:39,	dk:59},
        {nation: "Saudi Arabia",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"SA",	nationid:183,	asn:0,	lt:0,	md:54,	dk:46},
        {nation: "Singapore",	toptier:1,	nationstartingfirstletter:1,	groupid:81,	isocountry:"SG",	nationid:184,	asn:1,	lt:0,	md:90,	dk:10},
        {nation: "Sri Lanka",	toptier:1,	nationstartingfirstletter:1,	groupid:86,	isocountry:"LK",	nationid:185,	asn:1,	lt:0,	md:58,	dk:42},
        {nation: "Syria",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"SY",	nationid:186,	asn:0,	lt:0,	md:33,	dk:67},
        {nation: "Tajikistan",	toptier:1,	nationstartingfirstletter:1,	groupid:89,	isocountry:"TJ",	nationid:187,	asn:0,	lt:58,	md:42,	dk:0},
        {nation: "Thailand",	toptier:1,	nationstartingfirstletter:1,	groupid:90,	isocountry:"TH",	nationid:188,	asn:1,	lt:67,	md:33,	dk:0},
        {nation: "Turkmenistan",	toptier:1,	nationstartingfirstletter:1,	groupid:92,	isocountry:"TM",	nationid:189,	asn:0,	lt:58,	md:42,	dk:0},
        {nation: "United Arab Emirates",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"AE",	nationid:190,	asn:0,	lt:0,	md:33,	dk:67},
        {nation: "Uzbekistan",	toptier:1,	nationstartingfirstletter:1,	groupid:4,	isocountry:"UZ",	nationid:191,	asn:0,	lt:58,	md:42,	dk:0},
        {nation: "Vietnam",	toptier:1,	nationstartingfirstletter:1,	groupid:94,	isocountry:"VN",	nationid:192,	asn:1,	lt:33,	md:67,	dk:0},
        {nation: "Yemen",	toptier:1,	nationstartingfirstletter:1,	groupid:8,	isocountry:"YE",	nationid:193,	asn:0,	lt:0,	md:33,	dk:67},
        {nation: "American Samoa",	toptier:1,	nationstartingfirstletter:1,	groupid:79,	isocountry:"AS",	nationid:194,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Australia",	toptier:1,	nationstartingfirstletter:1,	groupid:38,	isocountry:"AU",	nationid:195,	asn:0,	lt:56,	md:26,	dk:18},
        {nation: "Cook Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:79,	isocountry:"CK",	nationid:196,	asn:0,	lt:33,	md:67,	dk:0},
        {nation: "Fiji",	toptier:1,	nationstartingfirstletter:1,	groupid:69,	isocountry:"FJ",	nationid:197,	asn:0,	lt:0,	md:33,	dk:67},
        {nation: "New Zealand",	toptier:1,	nationstartingfirstletter:1,	groupid:38,	isocountry:"NZ",	nationid:198,	asn:0,	lt:60,	md:34,	dk:6},
        {nation: "Papua New Guinea",	toptier:1,	nationstartingfirstletter:1,	groupid:69,	isocountry:"PG",	nationid:199,	asn:0,	lt:0,	md:90,	dk:10},
        {nation: "Samoa",	toptier:1,	nationstartingfirstletter:1,	groupid:79,	isocountry:"WS",	nationid:200,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Solomon Islands",	toptier:1,	nationstartingfirstletter:1,	groupid:69,	isocountry:"SB",	nationid:201,	asn:0,	lt:0,	md:33,	dk:67},
        {nation: "Tahiti",	toptier:1,	nationstartingfirstletter:1,	groupid:44,	isocountry:"PF",	nationid:202,	asn:1,	lt:0,	md:33,	dk:67},
        {nation: "Tonga",	toptier:1,	nationstartingfirstletter:1,	groupid:79,	isocountry:"TO",	nationid:203,	asn:1,	lt:0,	md:33,	dk:67},
        {nation: "Vanuatu",	toptier:1,	nationstartingfirstletter:1,	groupid:69,	isocountry:"VU",	nationid:204,	asn:1,	lt:0,	md:0,	dk:100},
        {nation: "Gibraltar",	toptier:1,	nationstartingfirstletter:1,	groupid:38,	isocountry:"GI",	nationid:205,	asn:0,	lt:33,	md:67,	dk:0},
        {nation: "Greenland",	toptier:1,	nationstartingfirstletter:1,	groupid:33,	isocountry:"GL",	nationid:206,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Dominican Republic",	toptier:1,	nationstartingfirstletter:1,	groupid:96,	isocountry:"DO",	nationid:207,	asn:0,	lt:0,	md:55,	dk:45},
        {nation: "Estonia",	toptier:1,	nationstartingfirstletter:1,	groupid:39,	isocountry:"EE",	nationid:208,	asn:0,	lt:100,	md:0,	dk:0},
        {nation: "Timor-Leste",	toptier:1,	nationstartingfirstletter:1,	groupid:6,	isocountry:"TL",	nationid:212,	asn:1,	lt:0,	md:100,	dk:0},
        {nation: "Chinese Taipei",	toptier:1,	nationstartingfirstletter:1,	groupid:9,	isocountry:"TW",	nationid:213,	asn:1,	lt:100,	md:0,	dk:0},
        {nation: "Comoros",	toptier:1,	nationstartingfirstletter:1,	groupid:43,	isocountry:"KM",	nationid:214,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "New Caledonia",	toptier:1,	nationstartingfirstletter:1,	groupid:44,	isocountry:"NC",	nationid:215,	asn:1,	lt:20,	md:60,	dk:20},
        {nation: "South Sudan",	toptier:1,	nationstartingfirstletter:1,	groupid:37,	isocountry:"SS",	nationid:218,	asn:0,	lt:0,	md:0,	dk:100},
        {nation: "Kosovo",	toptier:1,	nationstartingfirstletter:1,	groupid:13,	isocountry:"",	nationid:219,	asn:0,	lt:77,	md:23,	dk:0}
];									
}

function transfervaluestoovr(){
    return [	
        {transfervalue:"{Ignore}",	lo:65,hi:65},
        {transfervalue:"Less 3k",	lo:10,hi:19},
        {transfervalue:"€3k-€4.9k",	lo:20,hi:29},
        {transfervalue:"€5k-€6.9k",	lo:30,hi:39},
        {transfervalue:"€7k-€9.9k",	lo:40,hi:48},
        {transfervalue:"€10k-€24.9k",	lo:49,hi:50},
        {transfervalue:"€25k-€37.4k",	lo:50,hi:52},
        {transfervalue:"€37.5k-€49.9k",	lo:52,hi:54},
        {transfervalue:"€50k-€74.9k",	lo:55,hi:56},
        {transfervalue:"€75k-€99.9k",	lo:57,hi:59},
        {transfervalue:"€100k-€124.9k",	lo:60,hi:60},
        {transfervalue:"€125k-€149.9k",	lo:61,hi:61},
        {transfervalue:"€150k-€174.9k",	lo:61,hi:62},
        {transfervalue:"€175k-€199.9k",	lo:62,hi:62},
        {transfervalue:"€200k-€224.9k",	lo:63,hi:63},
        {transfervalue:"€225k-€274.9k",	lo:64,hi:64},
        {transfervalue:"€275k-€349.9k",	lo:65,hi:65},
        {transfervalue:"€350k-€449.9k",	lo:66,hi:66},
        {transfervalue:"€450k-€549.9k",	lo:67,hi:67},
        {transfervalue:"€550k-€649.9k",	lo:68,hi:68},
        {transfervalue:"€650k-€949.9k",	lo:69,hi:69},
        {transfervalue:"€950k-€1.32m",	lo:70,hi:70},
        {transfervalue:"€1.33m-€1.65m",	lo:71,hi:71},
        {transfervalue:"€1.66m-€1.99m",	lo:72,hi:72},
        {transfervalue:"€2m-€2.49m",	lo:73,hi:73},
        {transfervalue:"€2.5m-€3.49m",	lo:74,hi:74},
        {transfervalue:"€3.5m-€4.99m",	lo:75,hi:75},
        {transfervalue:"€5m-€6.99m",	lo:76,hi:76},
        {transfervalue:"€7m-€8.99m",	lo:77,hi:77},
        {transfervalue:"€9m-€11.99m",	lo:78,hi:78},
        {transfervalue:"€12m-€14.99m",	lo:79,hi:79},
        {transfervalue:"€15m-€19.99m",	lo:80,hi:80},
        {transfervalue:"€20m-€24.99m",	lo:81,hi:81},
        {transfervalue:"€25m-€29.99m",	lo:82,hi:82},
        {transfervalue:"€30m-€49.99m",	lo:83,hi:83},
        {transfervalue:"€50m-€91.99m",	lo:84,hi:84},
        {transfervalue:"€92m-€103.99m",	lo:85,hi:85},
        {transfervalue:"€104m-€108.99m",lo:86,hi:86},
        {transfervalue:"€109m-€116.49m",lo:87,hi:87},
        {transfervalue:"€116.5m-€129.9m",lo:88,hi:88},
        {transfervalue:"Greater €130m",	lo:89,hi:91},
            ];
}

function positions(){

    return [{id: 0,position: "GK"},
        {id: 1,position: "SW"},
        {id: 2,position: "RWB"},
        {id: 3,position: "RB"},
        {id: 4,position: "RCB"},
        {id: 5,position: "CB"},
        {id: 6,position: "LCB"},
        {id: 7,position: "LB"},
        {id: 8,position: "LWB"},
        {id: 9,position: "RDM"},
        {id: 10,position: "CDM"},
        {id: 11,position: "LDM"},
        {id: 12,position: "RM"},
        {id: 13,position: "RCM"},
        {id: 14,position: "CM"},
        {id: 15,position: "LCM"},
        {id: 16,position: "LM"},
        {id: 17,position: "RAM"},
        {id: 18,position: "CAM"},
        {id: 19,position: "LAM"},
        {id: 20,position: "RF"},
        {id: 21,position: "CF"},
        {id: 22,position: "LF"},
        {id: 23,position: "RW"},
        {id: 24,position: "RS"},
        {id: 25,position: "ST"},
        {id: 26,position: "LS"},
        {id: 27,position: "LW"}
        ];
}

